//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artgallery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Adminbox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adminbox()
        {
            this.ArtGalleries = new HashSet<ArtGallery>();
            this.ArtInvoices = new HashSet<ArtInvoice>();
            this.AuctionGalleries = new HashSet<AuctionGallery>();
            this.AuctionInvoices = new HashSet<AuctionInvoice>();
            this.Members = new HashSet<Member>();
        }
    
        public int adminId { get; set; }
        [Required]
        public string adminFirstName { get; set; }
        [Required]
        public string adminLastName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string adminPassword { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public string adminDOB { get; set; }
        [Required]
        public string adminAddress { get; set; }
        [Required]
        public string adminCity { get; set; }
        [Required]
        public string adminZip { get; set; }
        [Required]
        public string adminState { get; set; }
        [Required]
        public string adminCountry { get; set; }
        [Required]
        public string adminCellPhone { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string adminEmail { get; set; }
    

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtGallery> ArtGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtInvoice> ArtInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionGallery> AuctionGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionInvoice> AuctionInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
    }
}
