//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtGallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArtGallery()
        {
            this.ArtInvoices = new HashSet<ArtInvoice>();
        }
    
        public int ArtId { get; set; }
        public string ArtTitle { get; set; }
        public string ArtDescription { get; set; }
        public int ArtPrice { get; set; }
        public string ArtCategory { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public string approvalDate { get; set; }
        public Nullable<int> artistId_FK { get; set; }
        public Nullable<int> approvedbyadminid_FK { get; set; }
        public string ArtPic { get; set; }
    
        public virtual Adminbox Adminbox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtInvoice> ArtInvoices { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
