//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artgallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionGallery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuctionGallery()
        {
            this.AuctionInvoices = new HashSet<AuctionInvoice>();
        }
    
        public int AucId { get; set; }
        public string AucTitle { get; set; }
        public string AucDescription { get; set; }
        public string AucCategory { get; set; }
        public Nullable<int> Currentbid { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public string DateUploaded { get; set; }
        public string EndingDate { get; set; }
        public Nullable<int> ArtistId_FK { get; set; }
        public Nullable<int> Approvedbyadminid_FK { get; set; }
        public string AucPic { get; set; }
    
        public virtual Adminbox Adminbox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionInvoice> AuctionInvoices { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
