//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace artgallery.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.ArtGalleries = new HashSet<ArtGallery>();
            this.ArtInvoices = new HashSet<ArtInvoice>();
            this.AuctionGalleries = new HashSet<AuctionGallery>();
            this.AuctionInvoices = new HashSet<AuctionInvoice>();
        }
    
        public int memberId { get; set; }
        [Required]
        public string memberFirstName { get; set; }
        [Required]
        public string memberLastName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string memberPassword { get; set; }
        [Required]
        public string memberDOB { get; set; }
        [Required]
        public string memberAddress { get; set; }
        [Required]
        public string memberCity { get; set; }
        [Required]
        public string memberZip { get; set; }
        [Required]
        public string memberState { get; set; }
        [Required]
        public string memberCountry { get; set; }
        [Required]
        public string memberCellPhone { get; set; }
        [Required]
        public string memberEmail { get; set; }

        public string dateofjoining { get; set; }
        public Nullable<int> memberapprovedbyadminid_fk { get; set; }
        public Nullable<int> memberSoldProducts { get; set; }
        public Nullable<int> memberBuyedProducts { get; set; }
    
        public virtual Adminbox Adminbox { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtGallery> ArtGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArtInvoice> ArtInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionGallery> AuctionGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuctionInvoice> AuctionInvoices { get; set; }
    }
}
